### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by rabernat** [neurohackademy/nh2020-curriculum#42]
Hi! This is a great resource for python learners in many fields. Thanks so much for sharing it with the world. I just referenced it in a JOSS review as a source for best practices (see https://github.com/ihesp/IPART/issues/5), and as a result, a package copied some of your prose for a contributor guide (see https://github.com/ihesp/IPART/issues/6#issuecomment-667644155).

However, I noticed that this repo has no license. Could you please add one, so the usage rights are clear? Conversely, if this material is not meant to be openly licensed, I can stop sharing it.

**Comment by tyarkoni** [comment]
Hi @rabernat, thanks for bringing this up; we should have thought about (and addressed) this earlier. The main issue is that there are multiple contributors, so we can't just slap a permissive license on the entire repo without checking with instructors first. But I'll look into it and hopefully everyone signs off. Otherwise we can ask people to drop whatever license they're comfortable with into their own sub-folder.

**Comment by effigies** [comment]
FWIW I'm fine with any license up to CC0 for my contributions. I would vote against any stronger restriction than attribution.

**Comment by arokem** [comment]
Hi! I did put licenses in the folders that contain materials that I created. I figured that since this repo is an aggregation of materials from different authors, each one of the contributors could add their desired license and attribution to the part of the repo that they wrote. Does that make sense? In the end, we didn't enforce that broadly. Some of these materials were merged minutes before the lecture started 😄

**Comment by tyarkoni** [comment]
@arokem Nobody objected to a permissive license via email, and all of the responses were strongly supportive, so I think we can safely add a CC-BY license at root level. Any objections to that?

**Comment by arokem** [comment]
No objections! To be on the safe side, you could write that "unless
otherwise noted in individual folders, the license for the materials is CC
BY" and individual contributors can add their own licenses via PR, if they
want to apply something else to their materials.
